"""
Contributions to this module:
Miguel Sanda <msanda@arrobalytics.com>
Mando <mandonpolo@gmail.com>
"""

from django.urls import path, include

from aix import views

app_name = 'aix'

urlpatterns = [

    path('entity/', include('aix.urls.entity')),
    path('unit/', include('aix.urls.unit')),
    path('report/', include('aix.urls.report')),
    path('chart-of-accounts/', include('aix.urls.chart_of_accounts')),
    path('account/', include('aix.urls.account')),
    path('ledger/', include('aix.urls.ledger')),
    path('journal-entry/', include('aix.urls.journal_entry')),
    path('transactions/', include('aix.urls.transactions')),
    path('invoice/', include('aix.urls.invoice')),
    path('bill/', include('aix.urls.bill')),
    path('purchase_order/', include('aix.urls.purchase_order')),
    path('customer/', include('aix.urls.customer')),
    path('customer-job/', include('aix.urls.estimate')),
    path('customer-location/', include('aix.urls.customer_location')),
    path('vendor/', include('aix.urls.vendor')),
    path('item/', include('aix.urls.item')),
    path('bank-account/', include('aix.urls.bank_account')),
    path('data-import/', include('aix.urls.data_import')),
    path('auth/', include('aix.urls.auth')),
    path('feedback/', include('aix.urls.feedback')),
    path('inventory/', include('aix.urls.inventory')),
    # app urls
    path('absence-date/', include('aix.urls.absence_date')),
    path('absence-type/', include('aix.urls.absence_type')),
    path('asset/', include('aix.urls.asset')),
    path('its/', include('aix.urls.aix_its_status_report')),
    path('announcement/', include('aix.urls.announcement')),
    path('benefit-calculation/', include('aix.urls.benefit_calculation')),
    path('benefit-type/', include('aix.urls.benefit_type')),
    path('benefit/', include('aix.urls.benefit')),
    path('business-industry/', include('aix.urls.business_industry')),
    path('currency-rate/', include('aix.urls.currency_rate')),
    path('currency/', include('aix.urls.currency')),
    path('department/', include('aix.urls.department')),
    path('dependant/', include('aix.urls.dependant')),
    path('document-status/', include('aix.urls.document_status')),
    path('document-type/', include('aix.urls.document_type')),
    path('document/', include('aix.urls.document')),
    path('education/', include('aix.urls.education')),
    path('employee-assignment/', include('aix.urls.employee_assignment')),
    path('employee-avatar/', include('aix.urls.employee_avatar')),
    path('employee-contract-type/', include('aix.urls.employee_contract_type')),
    path('employee-contract/', include('aix.urls.employee_contract')),
    path('employee-faw/', include('aix.urls.employee_faw')),
    path('employee-language/', include('aix.urls.employee_language')),
    path('employee-license-detail/', include('aix.urls.employee_license_detail')),
    path('employee-license-type/', include('aix.urls.employee_license_type')),
    path('employee-of-the-week/', include('aix.urls.employee_of_the_week')),
    path('employee-payroll-benefit/', include('aix.urls.employee_payroll_benefit')),
    path('employee-payroll/', include('aix.urls.employee_payroll')),
    path('employee/', include('aix.urls.employee')),
    path('equipment/', include('aix.urls.equipment')),
    path('equipment_assignment/', include('aix.urls.equipment_assignment')),
    path('equipment_axle/', include('aix.urls.equipment_axle')),
    path('equipment_fet/', include('aix.urls.equipment_fet')),
    path('equipment_fuel/', include('aix.urls.equipment_fuel')),
    path('equipment_handover/', include('aix.urls.equipment_handover')),
    path('equipment_join/', include('aix.urls.equipment_join')),
    path('equipment_manufacturer/', include('aix.urls.equipment_manufacturer')),
    path('equipment_type/', include('aix.urls.equipment_type')),
    path('general-notification/', include('aix.urls.general_notification')),
    path('holiday/', include('aix.urls.holiday')),
    path('immigration-detail/', include('aix.urls.immigration_detail')),
    path('incoming-document-handler/', include('aix.urls.incoming_document_handler')),
    path('incoming-document-type/', include('aix.urls.incoming_document_type')),
    path('incoming-document/', include('aix.urls.incoming_document')),
    path('insurance-detail/', include('aix.urls.insurance_detail')),
    path('invoice-action/', include('aix.urls.invoice_action')),
    path('invoice-status/', include('aix.urls.invoice_status')),
    path('invoice-type/', include('aix.urls.invoice_type')),
    path('invoice/', include('aix.urls.invoice')),
    path('job/', include('aix.urls.job')),
    path('kpi-hse/', include('aix.urls.kpihse')),
    path('kpi-onoff/', include('aix.urls.kpionoff')),
    path('kpi-ops/', include('aix.urls.kpiops')),
    path('kpi-pob/', include('aix.urls.kpipob')),
    path('language/', include('aix.urls.language')),
    path('leave-card-carried-over/', include('aix.urls.leave_card_carried_over')),
    path('leave-card-detail/', include('aix.urls.leave_card_detail')),
    path('leave-card/', include('aix.urls.leave_card')),
    path('leave-request-action/', include('aix.urls.leave_request_action')),
    path('leave-request-detail/', include('aix.urls.leave_request_detail')),
    path('leave-request-status/', include('aix.urls.leave_request_status')),
    path('leave-request-workflow-action/', include('aix.urls.leave_request_workflow_action')),
    path('leave-request-workflow/', include('aix.urls.leave_request_workflow')),
    path('leave-request/', include('aix.urls.leave_request')),
    path('locations/', include('aix.urls.locations')),
    path('marital-status/', include('aix.urls.marital_status')),
    path('nation/', include('aix.urls.nation')),
    path('notification-external-type/', include('aix.urls.notification_external_type')),
    path('notification-tracker/', include('aix.urls.notification_tracker')),
    path('notification/', include('aix.urls.notification')),
    path('payment-mode/', include('aix.urls.payment_mode')),
    path('payroll-advance-request-action/', include('aix.urls.payroll_advance_request_action')),
    path('payroll-advance-request-detail/', include('aix.urls.payroll_advance_request_detail')),
    path('payroll-advance-request-status/', include('aix.urls.payroll_advance_request_status')),
    path('payroll-advance-request-workflow-action/', include('aix.urls.payroll_advance_request_workflow_action')),
    path('payroll-advance-request-workflow/', include('aix.urls.payroll_advance_request_workflow')),
    path('payroll-advance-request/', include('aix.urls.payroll_advance_request')),
    path('payroll-advance/', include('aix.urls.payroll_advance')),
    path('qualification/', include('aix.urls.qualification')),
#    path('received-email-document/', include('aix.urls.received_email_document')),
    path('relationship/', include('aix.urls.relationship')),
    path('report/', include('aix.urls.reporter')),
    path('requisition-action/', include('aix.urls.requisition_action')),
    path('requisition-category/', include('aix.urls.requisition_category')),
    path('requisition-flow-type/', include('aix.urls.requisition_flow_type')),
    path('requisition-status/', include('aix.urls.requisition_status')),
    path('requisition-workflow-action/', include('aix.urls.requisition_workflow_action')),
    path('requisition-workflow/', include('aix.urls.requisition_workflow')),
    path('requisition/', include('aix.urls.requisition')),
    path('route_survey/', include('aix.urls.route_survey')),
    path('route_survey_info/', include('aix.urls.route_survey_info')),
    path('salary/', include('aix.urls.salary')),
    path('skill/', include('aix.urls.skill')),
    path('settings/', include('aix.urls.settings')),
    path('task-assignee/', include('aix.urls.task_assignee')),
    path('task-status/', include('aix.urls.task_status')),
    path('task/', include('aix.urls.task')),
    path('tax/', include('aix.urls.tax')),
    path('visa/', include('aix.urls.visa')),
    path('weekend/', include('aix.urls.weekend')),
    path('weekly-employee-processed/', include('aix.urls.weekly_employee_processed')),
    path('weekly-employee/', include('aix.urls.weekly_employee')),
    path('work-order-activity/', include('aix.urls.work_order_activity')),
    path('work-order-activity-asset/', include('aix.urls.work_order_activity_asset')),
    path('work-order-activity-lifting/', include('aix.urls.work_order_activity_lifting')),
    path('work-order-activity-document/', include('aix.urls.work_order_activity_document')),
    path('work-order-activity-personnel/', include('aix.urls.work_order_activity_personnel')),
    path('work-order-activity-transport/', include('aix.urls.work_order_activity_transport')),
    path('work-category/', include('aix.urls.work_category')),
    path('work-order-status/', include('aix.urls.work_order_status')),
    path('work-order-jobcard-status/', include('aix.urls.work_order_jobcard_status')),
    path('work-order-jobcard/', include('aix.urls.work_order_jobcard')),
    path('work-order-task/', include('aix.urls.work_order_task')),
    path('work-order-task-asset/', include('aix.urls.work_order_task_asset')),
    path('work-order-task-personnel/', include('aix.urls.work_order_task_personnel')),
    path('work-order-type/', include('aix.urls.work_order_type')),
    path('work-order/', include('aix.urls.work_order')),
    path('work-order-asset/', include('aix.urls.work_order_asset')),
    path('work-order-personnel/', include('aix.urls.work_order_personnel')),
    path('workflow-action-type/', include('aix.urls.workflow_action_type')),
    path('workflow-action/', include('aix.urls.workflow_action')),
    path('workflow-status/', include('aix.urls.workflow_status')),
    path('workflow-type/', include('aix.urls.workflow_type')),
    path('workflow/', include('aix.urls.workflow')),

    path('home/', include('aix.urls.home')),
    path('djl-api/v1/', include('aix.urls.djl_api')),
    path('', views.RootUrlView.as_view(), name='root'),
]
