from django.urls import path

from aix import views

urlpatterns = [
     path('<slug:entity_slug>/latest/',
          views.PurchaseOrderModelListView.as_view(),
          name='po-list'),
     path('<slug:entity_slug>/year/<int:year>/',
          views.PurchaseOrderModelYearListView.as_view(),
          name='po-list-year'),
     path('<slug:entity_slug>/month/<int:year>/<int:month>/',
          views.PurchaseOrderModelMonthListView.as_view(),
          name='po-list-month'),
     path('<slug:entity_slug>/create/',
          views.PurchaseOrderModelCreateView.as_view(),
          name='po-create'),
     path('<slug:entity_slug>/create/estimate/<uuid:ce_pk>/',
          views.PurchaseOrderModelCreateView.as_view(for_estimate=True),
          name='po-create-estimate'),
     path('<slug:entity_slug>/detail/<uuid:po_pk>/',
          views.PurchaseOrderModelDetailView.as_view(),
          name='po-detail'),
     path('<slug:entity_slug>/update/<uuid:po_pk>/',
          views.PurchaseOrderModelUpdateView.as_view(),
          name='po-update'),
     path('<slug:entity_slug>/update/<uuid:po_pk>/update-items/',
          views.PurchaseOrderModelUpdateView.as_view(update_items=True),
          name='po-update-items'),
     path('<slug:entity_slug>/delete/<uuid:po_pk>/',
          views.PurchaseOrderModelDeleteView.as_view(),
          name='po-delete'),

     # Actions....
     path('<slug:entity_slug>/action/<uuid:po_pk>/mark-as-draft/',
          views.PurchaseOrderMarkAsDraftView.as_view(),
          name='po-action-mark-as-draft'),
     path('<slug:entity_slug>/action/<uuid:po_pk>/mark-as-review/',
          views.PurchaseOrderMarkAsReviewView.as_view(),
          name='po-action-mark-as-review'),
     path('<slug:entity_slug>/action/<uuid:po_pk>/mark-as-approved/',
          views.PurchaseOrderMarkAsApprovedView.as_view(),
          name='po-action-mark-as-approved'),
     path('<slug:entity_slug>/action/<uuid:po_pk>/mark-as-fulfilled/',
          views.PurchaseOrderMarkAsFulfilledView.as_view(),
          name='po-action-mark-as-fulfilled'),
     path('<slug:entity_slug>/action/<uuid:po_pk>/mark-as-canceled/',
          views.PurchaseOrderMarkAsCanceledView.as_view(),
          name='po-action-mark-as-canceled'),
     path('<slug:entity_slug>/action/<uuid:po_pk>/mark-as-void/',
          views.PurchaseOrderMarkAsVoidView.as_view(),
          name='po-action-mark-as-void'),
          
     # fuel
     path('<slug:entity_slug>/latest/fuel/',
          views.PurchaseOrderModelListView.as_view(po_active_module='fuel'),
          name='po-list-fuel'),
     path('<slug:entity_slug>/create/fuel',
          views.PurchaseOrderModelCreateView.as_view(po_active_module='fuel'),
          name='po-create-fuel'),
     path('<slug:entity_slug>/detail/fuel/<uuid:po_pk>/',
          views.PurchaseOrderModelDetailView.as_view(po_active_module='fuel'),
          name='po-detail-fuel'),
     path('<slug:entity_slug>/update/fuel/<uuid:po_pk>/',
          views.PurchaseOrderModelUpdateView.as_view(po_active_module='fuel'),
          name='po-update-fuel'),
     path('<slug:entity_slug>/update/fuel/<uuid:po_pk>/update-items/',
          views.PurchaseOrderModelUpdateView.as_view(update_items=True, po_active_module='fuel'),
          name='po-update-items-fuel'),
     # Actions....
     path('<slug:entity_slug>/action/fuel/<uuid:po_pk>/mark-as-draft/',
          views.PurchaseOrderMarkAsDraftView.as_view(po_active_module='fuel'),
          name='po-action-mark-as-draft-fuel'),
     path('<slug:entity_slug>/action/fuel/<uuid:po_pk>/mark-as-review/',
          views.PurchaseOrderMarkAsReviewView.as_view(po_active_module='fuel'),
          name='po-action-mark-as-review-fuel'),
     path('<slug:entity_slug>/action/fuel/<uuid:po_pk>/mark-as-approved/',
          views.PurchaseOrderMarkAsApprovedView.as_view(po_active_module='fuel'),
          name='po-action-mark-as-approved-fuel'),
     path('<slug:entity_slug>/action/fuel/<uuid:po_pk>/mark-as-fulfilled/',
          views.PurchaseOrderMarkAsFulfilledView.as_view(po_active_module='fuel'),
          name='po-action-mark-as-fulfilled-fuel'),
     path('<slug:entity_slug>/action/fuel/<uuid:po_pk>/mark-as-canceled/',
          views.PurchaseOrderMarkAsCanceledView.as_view(po_active_module='fuel'),
          name='po-action-mark-as-canceled-fuel'),
     path('<slug:entity_slug>/action/fuel/<uuid:po_pk>/mark-as-void/',
          views.PurchaseOrderMarkAsVoidView.as_view(po_active_module='fuel'),
          name='po-action-mark-as-void-fuel'),

     # reports
     
    path('<slug:entity_slug>/report/<uuid:po_pk>/',
         views.PurchaseOrderReportView.as_view(dwn_report_file=True),
         name='po-rpt'),
     
    path('<slug:entity_slug>/report/fuel/<uuid:po_pk>/',
         views.PurchaseOrderReportView.as_view(po_active_module='fuel', dwn_report_file=True),
         name='po-fuel-rpt'),
]
