from django.urls import path

from aix import views

urlpatterns = [
    path('<slug:entity_slug>/latest/',
         views.WorkOrderJobcardModelListView.as_view(),
         name='jcd-list'),
    path('<slug:entity_slug>/latest/<uuid:work_order_pk>/',
         views.WorkOrderJobcardModelListView.as_view(),
         name='jcd-list'),
    path('<slug:entity_slug>/year/<int:year>/',
         views.WorkOrderJobcardModelYearListView.as_view(),
         name='jcd-list-year'),
    path('<slug:entity_slug>/month/<int:year>/<int:month>/',
         views.WorkOrderJobcardModelMonthListView.as_view(),
         name='jcd-list-month'),
    path('<slug:entity_slug>/create/',
         views.WorkOrderJobcardModelCreateView.as_view(),
         name='jcd-create'),
    path('<slug:entity_slug>/create/wo/<uuid:work_order_pk>/',
         views.WorkOrderJobcardModelCreateView.as_view(for_work_order=True),
         name='jcd-create-work-order'),
    path('<slug:entity_slug>/create/wo/<uuid:work_order_pk>/<uuid:customer_pk>/',
         views.WorkOrderJobcardModelCreateView.as_view(for_work_order=True),
         name='jcd-create-work-order-customer'),
    path('<slug:entity_slug>/detail/<uuid:jcd_pk>/',
         views.WorkOrderJobcardModelDetailView.as_view(),
         name='jcd-detail'),
    path('<slug:entity_slug>/update/<uuid:jcd_pk>/',
         views.WorkOrderJobcardModelUpdateView.as_view(),
         name='jcd-update'),
    path('<slug:entity_slug>/update/<uuid:jcd_pk>/update-items/',
         views.WorkOrderJobcardModelUpdateView.as_view(update_items=True),
         name='jcd-update-items'),
    path('<slug:entity_slug>/delete/<uuid:jcd_pk>/',
         views.WorkOrderJobcardModelDeleteView.as_view(),
         name='jcd-delete'),

    # Actions....
    path('<slug:entity_slug>/action/<uuid:jcd_pk>/mark-as-draft/',
         views.WorkOrderJobcardMarkAsDraftView.as_view(),
         name='jcd-action-mark-as-draft'),
    path('<slug:entity_slug>/action/<uuid:jcd_pk>/mark-as-review/',
         views.WorkOrderJobcardMarkAsReviewView.as_view(),
         name='jcd-action-mark-as-review'),
    path('<slug:entity_slug>/action/<uuid:jcd_pk>/mark-as-approved/',
         views.WorkOrderJobcardMarkAsApprovedView.as_view(),
         name='jcd-action-mark-as-approved'),
    path('<slug:entity_slug>/action/<uuid:jcd_pk>/mark-as-fulfilled/',
         views.WorkOrderJobcardMarkAsFulfilledView.as_view(),
         name='jcd-action-mark-as-fulfilled'),
    path('<slug:entity_slug>/action/<uuid:jcd_pk>/mark-as-canceled/',
         views.WorkOrderJobcardMarkAsCanceledView.as_view(),
         name='jcd-action-mark-as-canceled'),
    path('<slug:entity_slug>/action/<uuid:jcd_pk>/mark-as-void/',
         views.WorkOrderJobcardMarkAsVoidView.as_view(),
         name='jcd-action-mark-as-void'),
     
     # reports
     
    path('<slug:entity_slug>/report/<uuid:jcd_pk>/',
         views.WorkOrderJobcardReportView.as_view(dwn_report_file=True),
         name='jcd-rpt'),
]
