# Generated by Django 4.2.7 on 2024-04-05 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpiopsmodel',
            name='equipment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='aix.assetmodel', verbose_name='Equipment'),
            preserve_default=False,
        ),
    ]
