# Generated by Django 5.1 on 2025-01-06 12:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aix', '0004_rename_aix_absenc_created_250d79_idx_aix_absence_created_134fa8_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AixItsStatusReportModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default='NA', max_length=100)),
                ('activity', models.CharField(max_length=100)),
                ('activity_type', models.CharField(blank=True, choices=[('General', 'General'), ('IT Support', 'IT Support'), ('Troubleshooting', 'Troubleshooting')], default='IMMEDIATE', max_length=255, null=True)),
                ('startdate', models.DateField(blank=True, db_column='startDate', null=True)),
                ('dueDate', models.DateField(blank=True, db_column='dueDate', null=True)),
                ('status', models.CharField(blank=True, choices=[('NEW', 'NEW'), ('IN PROGRESS', 'IN PROGRESS'), ('DELAYED', 'DELAYED'), ('POSTPONED', 'POSTPONED'), ('COMPLETED', 'COMPLETED')], default='IN PROGRESS', max_length=255, null=True)),
                ('priorities', models.CharField(blank=True, choices=[('IMMEDIATE', 'IMMEDIATE'), ('LONG TERM', 'LONG TERM'), ('SHORT TERM', 'SHORT TERM'), ('QUARTERLY', 'QUARTERLY'), ('YEARLY', 'YEARLY')], default='General', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('entity', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='aix.entitymodel', verbose_name='Entity')),
            ],
            options={
                'verbose_name': 'Systems Support Status',
                'indexes': [models.Index(fields=['created'], name='aix_aixitss_created_1900ba_idx'), models.Index(fields=['updated'], name='aix_aixitss_updated_7081b6_idx'), models.Index(fields=['activity'], name='aix_aixitss_activit_314e97_idx')],
                'unique_together': {('entity', 'activity', 'status')},
            },
        ),
    ]
