# Generated by Django 5.1 on 2025-01-06 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aix', '0005_aixitsstatusreportmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aixitsstatusreportmodel',
            old_name='priorities',
            new_name='priority',
        ),
    ]
