# Generated by Django 5.1 on 2025-01-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aix', '0006_rename_priorities_aixitsstatusreportmodel_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='aixitsstatusreportmodel',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
