# Generated by Django 5.1 on 2025-01-08 07:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aix', '0007_aixitsstatusreportmodel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentAxleModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('entity', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='aix.entitymodel', verbose_name='Equipment Axle Entity')),
            ],
            options={
                'verbose_name': 'Equipment Axle',
            },
        ),
        migrations.CreateModel(
            name='EquipmentManufacturerModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default='NA', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('entity', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='aix.entitymodel', verbose_name='Equipment Manufacturer Entity')),
            ],
            options={
                'verbose_name': 'Equipment Manufacturer',
            },
        ),
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('address_1', models.CharField(max_length=70, verbose_name='Address Line 1')),
                ('address_2', models.CharField(blank=True, max_length=70, null=True, verbose_name='Address Line 2')),
                ('city', models.CharField(blank=True, max_length=70, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=70, null=True, verbose_name='State/Province')),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Zip Code')),
                ('country', models.CharField(blank=True, max_length=70, null=True, verbose_name='Country')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone Number')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reg_no', models.CharField(max_length=255, unique=True)),
                ('yom', models.DateField(blank=True, null=True)),
                ('model', models.CharField(max_length=255)),
                ('horse_power', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('fuel_ratio', models.FloatField(blank=True, null=True)),
                ('chassis', models.CharField(blank=True, max_length=255, null=True)),
                ('engine_no', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_entity', to='aix.entitymodel', verbose_name='Equipment Entity')),
                ('eq_axle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aix.equipmentaxlemodel', verbose_name='Equipment Axle')),
                ('eq_manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aix.equipmentmanufacturermodel', verbose_name='Equipment Manufacturer')),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aix.nationmodel', verbose_name='Nation')),
            ],
            options={
                'verbose_name': 'Equipment',
            },
        ),
        migrations.CreateModel(
            name='AixItsHandOverModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default='NA', max_length=100)),
                ('equipment_condition', models.CharField(max_length=100)),
                ('proper_use', models.CharField(blank=True, choices=[('OFFICIAL', 'OFFICIAL'), ('PERSONAL', 'PERSONAL')], default='OFFICAL', max_length=255, null=True)),
                ('description', models.TextField()),
                ('issue_date', models.DateField(blank=True, db_column='issueDate', null=True)),
                ('return_date', models.DateField(blank=True, db_column='returnDate', null=True)),
                ('status', models.CharField(blank=True, choices=[('DRAFT', 'DRAFT'), ('APPROVED', 'APPROVED')], default='APPROVED', max_length=255, null=True)),
                ('entity', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='aix.entitymodel', verbose_name='Entity')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aix.employeemodel', verbose_name='Staff')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='aix.equipmentmodel', verbose_name='Equipment')),
            ],
            options={
                'verbose_name': 'Systems Support Status',
            },
        ),
        migrations.CreateModel(
            name='EquipmentTypeModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default='NA', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('entity', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='aix.entitymodel', verbose_name='Equipment Type Entity')),
            ],
            options={
                'verbose_name': 'Equipment Type',
            },
        ),
        migrations.AddField(
            model_name='equipmentmodel',
            name='eq_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aix.equipmenttypemodel', verbose_name='Equipment Type'),
        ),
        migrations.AddIndex(
            model_name='equipmentaxlemodel',
            index=models.Index(fields=['created'], name='aix_equipme_created_cbe96c_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentaxlemodel',
            index=models.Index(fields=['updated'], name='aix_equipme_updated_c43da8_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentaxlemodel',
            index=models.Index(fields=['name'], name='aix_equipme_name_c69081_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='equipmentaxlemodel',
            unique_together={('entity', 'code')},
        ),
        migrations.AddIndex(
            model_name='equipmentmanufacturermodel',
            index=models.Index(fields=['created'], name='aix_equipme_created_ff2342_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentmanufacturermodel',
            index=models.Index(fields=['updated'], name='aix_equipme_updated_cb1265_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentmanufacturermodel',
            index=models.Index(fields=['name'], name='aix_equipme_name_a51cd4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='equipmentmanufacturermodel',
            unique_together={('entity', 'code')},
        ),
        migrations.AddIndex(
            model_name='aixitshandovermodel',
            index=models.Index(fields=['created'], name='aix_aixitsh_created_99a6cb_idx'),
        ),
        migrations.AddIndex(
            model_name='aixitshandovermodel',
            index=models.Index(fields=['updated'], name='aix_aixitsh_updated_4af488_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='aixitshandovermodel',
            unique_together={('entity', 'equipment', 'staff', 'status')},
        ),
        migrations.AddIndex(
            model_name='equipmenttypemodel',
            index=models.Index(fields=['created'], name='aix_equipme_created_1897a8_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmenttypemodel',
            index=models.Index(fields=['updated'], name='aix_equipme_updated_d89575_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmenttypemodel',
            index=models.Index(fields=['name'], name='aix_equipme_name_515932_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='equipmenttypemodel',
            unique_together={('entity', 'code')},
        ),
        migrations.AddIndex(
            model_name='equipmentmodel',
            index=models.Index(fields=['created'], name='aix_equipme_created_af845b_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentmodel',
            index=models.Index(fields=['updated'], name='aix_equipme_updated_d4b5a2_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentmodel',
            index=models.Index(fields=['is_active'], name='aix_equipme_is_acti_6c48d8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='equipmentmodel',
            unique_together={('entity', 'reg_no')},
        ),
    ]
