# Generated by Django 5.1 on 2025-01-24 08:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aix', '0008_equipmentaxlemodel_equipmentmanufacturermodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentAssignmentModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('address_1', models.CharField(max_length=70, verbose_name='Address Line 1')),
                ('address_2', models.CharField(blank=True, max_length=70, null=True, verbose_name='Address Line 2')),
                ('city', models.CharField(blank=True, max_length=70, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=70, null=True, verbose_name='State/Province')),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Zip Code')),
                ('country', models.CharField(blank=True, max_length=70, null=True, verbose_name='Country')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone Number')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('is_supervisor', models.BooleanField(default=False)),
                ('is_assistant', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Equipment Assignment',
            },
        ),
        migrations.CreateModel(
            name='EquipmentJoinModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('address_1', models.CharField(max_length=70, verbose_name='Address Line 1')),
                ('address_2', models.CharField(blank=True, max_length=70, null=True, verbose_name='Address Line 2')),
                ('city', models.CharField(blank=True, max_length=70, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=70, null=True, verbose_name='State/Province')),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Zip Code')),
                ('country', models.CharField(blank=True, max_length=70, null=True, verbose_name='Country')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone Number')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Equipment Join',
            },
        ),
        migrations.RemoveIndex(
            model_name='equipmentmodel',
            name='aix_equipme_is_acti_6c48d8_idx',
        ),
        migrations.RenameField(
            model_name='aixitsstatusreportmodel',
            old_name='dueDate',
            new_name='duedate',
        ),
        migrations.RenameField(
            model_name='equipmentmodel',
            old_name='is_active',
            new_name='active',
        ),
        migrations.AlterField(
            model_name='jobapplicantmodel',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Job_Applicant_Entity', to='aix.entitymodel', verbose_name='JobApplicant Entity'),
        ),
        migrations.AddIndex(
            model_name='equipmentmodel',
            index=models.Index(fields=['active'], name='aix_equipme_active_6e1580_idx'),
        ),
        migrations.AddField(
            model_name='equipmentassignmentmodel',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_assignment_entity', to='aix.entitymodel', verbose_name='EquipmentAssignment Entity'),
        ),
        migrations.AddField(
            model_name='equipmentassignmentmodel',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aix.equipmentmodel', verbose_name='Equipment'),
        ),
        migrations.AddField(
            model_name='equipmentassignmentmodel',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aix.employeemodel', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='equipmentjoinmodel',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Equipment_Join_Entity', to='aix.entitymodel', verbose_name='EquipmentJoin Entity'),
        ),
        migrations.AddField(
            model_name='equipmentjoinmodel',
            name='eq_primary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_equipment', to='aix.equipmentmodel', verbose_name='Equipment'),
        ),
        migrations.AddField(
            model_name='equipmentjoinmodel',
            name='eq_secondary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_equipment', to='aix.equipmentmodel', verbose_name='Equipment'),
        ),
        migrations.AddIndex(
            model_name='equipmentassignmentmodel',
            index=models.Index(fields=['created'], name='aix_equipme_created_a8b458_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentassignmentmodel',
            index=models.Index(fields=['updated'], name='aix_equipme_updated_d6e6d6_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentassignmentmodel',
            index=models.Index(fields=['is_active'], name='aix_equipme_is_acti_272633_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='equipmentassignmentmodel',
            unique_together={('entity', 'date', 'equipment', 'operator')},
        ),
        migrations.AddIndex(
            model_name='equipmentjoinmodel',
            index=models.Index(fields=['created'], name='aix_equipme_created_328d84_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentjoinmodel',
            index=models.Index(fields=['updated'], name='aix_equipme_updated_366182_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentjoinmodel',
            index=models.Index(fields=['is_active'], name='aix_equipme_is_acti_cef0af_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='equipmentjoinmodel',
            unique_together={('entity', 'date', 'eq_primary', 'eq_secondary', 'is_active')},
        ),
    ]
