# Generated by Django 5.1 on 2025-03-31 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aix', '0009_equipmentassignmentmodel_equipmentjoinmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentmodel',
            name='chassis',
        ),
        migrations.RemoveField(
            model_name='equipmentmodel',
            name='engine_no',
        ),
        migrations.RemoveField(
            model_name='equipmentmodel',
            name='eq_axle',
        ),
        migrations.RemoveField(
            model_name='equipmentmodel',
            name='fuel_ratio',
        ),
        migrations.RemoveField(
            model_name='equipmentmodel',
            name='horse_power',
        ),
        migrations.RemoveField(
            model_name='equipmentmodel',
            name='nation',
        ),
    ]
