# Generated by Django 5.1 on 2025-03-31 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aix', '0010_remove_equipmentmodel_chassis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentmodel',
            name='yom',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
