# Generated by Django 5.1 on 2025-03-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aix', '0011_alter_equipmentmodel_yom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentmodel',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
