# Generated by Django 5.1 on 2025-03-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aix', '0012_alter_equipmentmodel_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentmodel',
            name='serial',
            field=models.CharField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
