# Generated by Django 5.1 on 2025-03-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aix', '0014_equipmentmodel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenttypemodel',
            name='code',
            field=models.CharField(max_length=100),
        ),
    ]
