# Generated by Django 5.1 on 2025-04-01 07:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aix', '0015_alter_equipmenttypemodel_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentHandoverModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('address_1', models.CharField(max_length=70, verbose_name='Address Line 1')),
                ('address_2', models.CharField(blank=True, max_length=70, null=True, verbose_name='Address Line 2')),
                ('city', models.CharField(blank=True, max_length=70, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=70, null=True, verbose_name='State/Province')),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Zip Code')),
                ('country', models.CharField(blank=True, max_length=70, null=True, verbose_name='Country')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone Number')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('ho_date', models.DateField(blank=True, null=True)),
                ('ho_time', models.TimeField()),
                ('project', models.CharField(choices=[('RG1501', 'Rig Move 1501'), ('RG1502', 'Rig Move 1502'), ('RG1503', 'Rig Move 1503'), ('KFDA', 'King Fisher Oil Field'), ('CPP', 'CPP')], max_length=100)),
                ('dho', models.TextField(blank=True, null=True)),
                ('condition', models.CharField(choices=[('GOOD', 'GOOD'), ('FAULTY', 'FAULTY'), ('DAMAGED', 'DAMAGED'), ('FOR REPAIR', 'FOR REPAIR'), ('FOR REPLACEPMENT', 'FOR REPLACEPMENT')], max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_handover_entity', to='aix.entitymodel', verbose_name='EquipmentHandover Entity')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aix.equipmentmodel', verbose_name='Items Handed Over')),
                ('handover_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='equipment_handover_by', to='aix.employeemodel', verbose_name='Handover By')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aix.customerlocationmodel', verbose_name='Customer Location')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='equipment_received_by', to='aix.employeemodel', verbose_name='Received By')),
            ],
            options={
                'verbose_name': 'Equipment Handover',
                'indexes': [models.Index(fields=['created'], name='aix_equipme_created_aa3bbf_idx'), models.Index(fields=['updated'], name='aix_equipme_updated_b50d04_idx'), models.Index(fields=['is_active'], name='aix_equipme_is_acti_dc8718_idx')],
                'unique_together': {('entity', 'ho_date', 'equipment', 'handover_by', 'received_by')},
            },
        ),
    ]
