# Generated by Django 5.1 on 2025-04-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aix', '0016_equipmenthandovermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentmodel',
            name='reg_no',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
