# Generated by Django 5.1 on 2025-04-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aix', '0017_alter_equipmentmodel_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentmodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
