# Generated by Django 5.1 on 2025-05-06 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aix', '0018_alter_equipmentmodel_active'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_by_hr',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approved_by_hr', to='aix.employeemodel', verbose_name='Approved By HR'),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_by_ict',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approved_by_ict', to='aix.employeemodel', verbose_name='Approved By ICT'),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_date_hr',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_date_ict',
        #     field=models.DateField(blank=True, null=True),
        # ),
        migrations.AddField(
            model_name='equipmenthandovermodel',
            name='purpose',
            field=models.CharField(choices=[('OFF', 'OFFICIAL'), ('UNOFF', 'UN-OFFICIAL'), ('EXT', 'EXTERNAL'), ('FOC', 'FOR CLIENT USE')], default=0, max_length=100),
            preserve_default=False,
        ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='return_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
    ]
