# Generated by Django 5.1 on 2025-05-14 07:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aix', '0019_equipmenthandovermodel_approved_by_hr_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_by_hr',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approved_by_hr', to='aix.employeemodel', verbose_name='Approved By HR'),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_by_ict',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approved_by_ict', to='aix.employeemodel', verbose_name='Approved By ICT'),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_date_hr',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_date_ict',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='return_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='equipmenthandovermodel',
        #     name='purpose',
        #     field=models.CharField(choices=[('OFF', 'OFFICIAL'), ('UNOFF', 'UN-OFFICIAL'), ('FOH', 'FOR HIRE'), ('EXT', 'EXTERNAL')], max_length=100),
        # ),
        migrations.CreateModel(
            name='RouteSurveyInfoModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('route_code', models.CharField(max_length=100)),
                ('south_coordinate', models.CharField(max_length=100)),
                ('east_coordinate', models.CharField(max_length=100)),
                ('distance_start', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('RED', 'RED'), ('AMBER', 'AMBER'), ('GREEN', 'GREEN')], max_length=50)),
                ('koc', models.CharField(choices=[('RED', 'RED'), ('AMBER', 'AMBER'), ('GREEN', 'GREEN')], max_length=50)),
                ('kfi_description', models.TextField(blank=True, null=True)),
                ('photo', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('entity', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='aix.entitymodel', verbose_name='RouteSurveyInfo Entity')),
                ('route_survey', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='route_survey_info', to='aix.routesurveyinfomodel', verbose_name='RouteSurveyInfo')),
            ],
            options={
                'verbose_name': 'RouteSurveyInfo',
                'indexes': [models.Index(fields=['created'], name='aix_routesu_created_e96eb5_idx'), models.Index(fields=['updated'], name='aix_routesu_updated_ff2cb1_idx'), models.Index(fields=['south_coordinate'], name='aix_routesu_south_c_c5b56f_idx'), models.Index(fields=['east_coordinate'], name='aix_routesu_east_co_f2b58a_idx')],
                'unique_together': {('entity', 'south_coordinate', 'east_coordinate', 'route_survey')},
            },
        ),
        migrations.CreateModel(
            name='RouteSurveyModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_place', models.CharField(max_length=100)),
                ('via_place', models.CharField(max_length=100)),
                ('end_place', models.CharField(max_length=100)),
                ('start_gps', models.CharField(max_length=100)),
                ('via_gps', models.CharField(max_length=100)),
                ('end_gps', models.CharField(max_length=100)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('genera_notes', models.TextField(blank=True, null=True)),
                ('bo1', models.TextField(blank=True, null=True)),
                ('bo2', models.TextField(blank=True, null=True)),
                ('bo3', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('entity', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='aix.entitymodel', verbose_name='RouteSurvey Entity')),
            ],
            options={
                'verbose_name': 'RouteSurvey',
                'indexes': [models.Index(fields=['created'], name='aix_routesu_created_4ff5b0_idx'), models.Index(fields=['updated'], name='aix_routesu_updated_4a8786_idx'), models.Index(fields=['start_gps'], name='aix_routesu_start_g_6bbec2_idx'), models.Index(fields=['end_gps'], name='aix_routesu_end_gps_b68e87_idx')],
                'unique_together': {('entity', 'start_date', 'end_date', 'start_place', 'end_place')},
            },
        ),
    ]
