# Generated by Django 5.1 on 2025-05-14 11:33

import django.db.models.deletion
import django_google_maps.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aix', '0020_equipmenthandovermodel_approved_by_hr_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_by_hr',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approved_by_hr', to='aix.employeemodel', verbose_name='Approved By HR'),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_by_ict',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approved_by_ict', to='aix.employeemodel', verbose_name='Approved By ICT'),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_date_hr',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_date_ict',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='return_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
        migrations.AlterField(
            model_name='equipmenthandovermodel',
            name='purpose',
            field=models.CharField(choices=[('OFF', 'OFFICIAL'), ('UNOFF', 'UN-OFFICIAL'), ('FOH', 'FOR HIRE'), ('EXT', 'EXTERNAL')], max_length=100),
        ),
        migrations.AlterField(
            model_name='routesurveymodel',
            name='end_gps',
            field=django_google_maps.fields.GeoLocationField(max_length=100),
        ),
        migrations.AlterField(
            model_name='routesurveymodel',
            name='end_place',
            field=django_google_maps.fields.AddressField(max_length=200),
        ),
        migrations.AlterField(
            model_name='routesurveymodel',
            name='start_gps',
            field=django_google_maps.fields.GeoLocationField(max_length=100),
        ),
        migrations.AlterField(
            model_name='routesurveymodel',
            name='start_place',
            field=django_google_maps.fields.AddressField(max_length=200),
        ),
        migrations.AlterField(
            model_name='routesurveymodel',
            name='via_gps',
            field=django_google_maps.fields.GeoLocationField(max_length=100),
        ),
        migrations.AlterField(
            model_name='routesurveymodel',
            name='via_place',
            field=django_google_maps.fields.AddressField(max_length=200),
        ),
    ]
