# Generated by Django 5.1 on 2025-05-15 08:28

import django.db.models.deletion
import map_location.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aix', '0021_equipmenthandovermodel_approved_by_hr_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_by_hr',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approved_by_hr', to='aix.employeemodel', verbose_name='Approved By HR'),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_by_ict',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approved_by_ict', to='aix.employeemodel', verbose_name='Approved By ICT'),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_date_hr',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_date_ict',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='return_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
        migrations.AddField(
            model_name='routesurveymodel',
            name='location',
            field=map_location.fields.LocationField(blank=True, null=True, verbose_name='Pos'),
        ),
    ]
