# Generated by Django 5.1.4 on 2025-07-10 09:19

import django.db.models.deletion
import location_field.models.plain
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aix', '0023_equipmenthandovermodel_approved_by_hr_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_by_hr',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approved_by_hr', to='aix.employeemodel', verbose_name='Approved By HR'),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_by_ict',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approved_by_ict', to='aix.employeemodel', verbose_name='Approved By ICT'),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_date_hr',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_date_ict',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='return_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='routesurveymodel',
        #     name='end_gps',
        #     field=models.CharField(max_length=100),
        # ),
        # migrations.AlterField(
        #     model_name='routesurveymodel',
        #     name='end_place',
        #     field=models.CharField(max_length=200),
        # ),
        # migrations.AlterField(
        #     model_name='routesurveymodel',
        #     name='location',
        #     field=location_field.models.plain.PlainLocationField(default=0, max_length=63),
        #     preserve_default=False,
        # ),
        # migrations.AlterField(
        #     model_name='routesurveymodel',
        #     name='start_gps',
        #     field=models.CharField(max_length=100),
        # ),
        # migrations.AlterField(
        #     model_name='routesurveymodel',
        #     name='start_place',
        #     field=models.CharField(max_length=200),
        # ),
        # migrations.AlterField(
        #     model_name='routesurveymodel',
        #     name='via_gps',
        #     field=models.CharField(max_length=100),
        # ),
        # migrations.AlterField(
        #     model_name='routesurveymodel',
        #     name='via_place',
        #     field=models.CharField(max_length=200),
        # ),
        migrations.CreateModel(
            name='EmployeeFawModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('faw_date', models.DateField(blank=True, null=True)),
                ('entity', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='aix.entitymodel', verbose_name='EmployeeFaw Entity')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aix.customerlocationmodel', verbose_name='Customer Location')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aix.workordermodel', verbose_name='Work Order')),
            ],
            options={
                'verbose_name': 'EmployeeFaw',
            },
        ),
        migrations.CreateModel(
            name='ItemFawModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, verbose_name='ItemFaw Name')),
                ('attendance_code', models.CharField(blank=True, choices=[('P', 'PRESENT'), ('S', 'SICK'), ('L', 'LEAVE'), ('A', 'ABSENT'), ('MOB', 'Move To Work Site'), ('DMB', 'DEMMOBED')], max_length=10, null=True)),
                ('attendance_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aix.employeemodel', verbose_name='Employee')),
                ('entity', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='items_faw', to='aix.entitymodel', verbose_name='ItemFaw Entity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemFawThroughModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attendance_code', models.CharField(blank=True, choices=[('P', 'PRESENT'), ('S', 'SICK'), ('L', 'LEAVE'), ('A', 'ABSENT'), ('MOB', 'Move To Work Site'), ('DMB', 'DEMMOBED')], max_length=10, null=True)),
                ('attendance_date', models.DateField(auto_now_add=True)),
                ('faw_item_status', models.CharField(blank=True, choices=[('completed', 'Completed'), ('canceled', 'Canceled')], max_length=15, null=True, verbose_name='FAW Item Status')),
                ('entity_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='aix.entityunitmodel', verbose_name='Associated Branch')),
                ('faw_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='aix.employeefawmodel', verbose_name='FAW Model')),
                ('item_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aix.itemfawmodel', verbose_name='ItemFaw Model')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_set', to='aix.itemfawthroughmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='employeefawmodel',
            index=models.Index(fields=['created'], name='aix_employe_created_19c4c2_idx'),
        ),
        migrations.AddIndex(
            model_name='employeefawmodel',
            index=models.Index(fields=['updated'], name='aix_employe_updated_175664_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employeefawmodel',
            unique_together={('entity', 'faw_date')},
        ),
        migrations.AddIndex(
            model_name='itemfawmodel',
            index=models.Index(fields=['is_active'], name='aix_itemfaw_is_acti_1baf49_idx'),
        ),
        migrations.AddIndex(
            model_name='itemfawmodel',
            index=models.Index(fields=['attendance_code'], name='aix_itemfaw_attenda_fae22a_idx'),
        ),
        migrations.AddIndex(
            model_name='itemfawmodel',
            index=models.Index(fields=['entity', 'attendance_code'], name='aix_itemfaw_entity__df2a15_idx'),
        ),
        migrations.AddIndex(
            model_name='itemfawthroughmodel',
            index=models.Index(fields=['faw_model', 'item_model'], name='aix_itemfaw_faw_mod_e5e8b0_idx'),
        ),
        migrations.AddIndex(
            model_name='itemfawthroughmodel',
            index=models.Index(fields=['faw_item_status'], name='aix_itemfaw_faw_ite_8abca4_idx'),
        ),
    ]
