# Generated by Django 5.1.4 on 2025-07-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aix', '0029_equipmenthandovermodel_approved_by_hr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeefawmodel',
            name='faw_items',
            field=models.ManyToManyField(through='aix.ItemFawThroughModel', to='aix.employeemodel', verbose_name='FAW Items'),
        ),
    ]
