# Generated by Django 5.1.4 on 2025-07-14 13:21

import django.db.models.deletion
import location_field.models.plain
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aix', '0030_alter_employeefawmodel_faw_items'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='itemfawthroughmodel',
            name='aix_itemfaw_faw_mod_e5e8b0_idx',
        ),
        migrations.RemoveField(
            model_name='itemfawthroughmodel',
            name='item_model',
        ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_by_hr',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approved_by_hr', to='aix.employeemodel', verbose_name='Approved By HR'),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_by_ict',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approved_by_ict', to='aix.employeemodel', verbose_name='Approved By ICT'),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_date_hr',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_date_ict',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='return_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='routesurveymodel',
        #     name='end_gps',
        #     field=models.CharField(max_length=100),
        # ),
        # migrations.AlterField(
        #     model_name='routesurveymodel',
        #     name='end_place',
        #     field=models.CharField(max_length=200),
        # ),
        # migrations.AlterField(
        #     model_name='routesurveymodel',
        #     name='location',
        #     field=location_field.models.plain.PlainLocationField(default=0, max_length=63),
        #     preserve_default=False,
        # ),
        # migrations.AlterField(
        #     model_name='routesurveymodel',
        #     name='start_gps',
        #     field=models.CharField(max_length=100),
        # ),
        # migrations.AlterField(
        #     model_name='routesurveymodel',
        #     name='start_place',
        #     field=models.CharField(max_length=200),
        # ),
        # migrations.AlterField(
        #     model_name='routesurveymodel',
        #     name='via_gps',
        #     field=models.CharField(max_length=100),
        # ),
        # migrations.AlterField(
        #     model_name='routesurveymodel',
        #     name='via_place',
        #     field=models.CharField(max_length=200),
        # ),
        migrations.AddIndex(
            model_name='itemfawthroughmodel',
            index=models.Index(fields=['faw_model', 'employee_model'], name='aix_itemfaw_faw_mod_4af1f1_idx'),
        ),
    ]
