# Generated by Django 5.1.4 on 2025-07-17 13:32

import django.db.models.deletion
import location_field.models.plain
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aix', '0035_equipmenthandovermodel_approved_by_hr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeefawmodel',
            name='markdown_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Markdown Notes'),
        ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_by_hr',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approved_by_hr', to='aix.employeemodel', verbose_name='Approved By HR'),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_by_ict',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approved_by_ict', to='aix.employeemodel', verbose_name='Approved By ICT'),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_date_hr',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_date_ict',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='return_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
        migrations.AlterField(
            model_name='employeefawmodel',
            name='faw_status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'), ('fulfilled', 'fulfilled'), ('paid', 'Paid'), ('canceled', 'Canceled'), ('void', 'Void')], default='draft', max_length=15, null=True, verbose_name='FAW Item Status'),
        ),
        # migrations.AlterField(
        #     model_name='routesurveymodel',
        #     name='end_gps',
        #     field=models.CharField(max_length=100),
        # ),
        # migrations.AlterField(
        #     model_name='routesurveymodel',
        #     name='end_place',
        #     field=models.CharField(max_length=200),
        # ),
        # migrations.AlterField(
        #     model_name='routesurveymodel',
        #     name='location',
        #     field=location_field.models.plain.PlainLocationField(default=0, max_length=63),
        #     preserve_default=False,
        # ),
        # migrations.AlterField(
        #     model_name='routesurveymodel',
        #     name='start_gps',
        #     field=models.CharField(max_length=100),
        # ),
        # migrations.AlterField(
        #     model_name='routesurveymodel',
        #     name='start_place',
        #     field=models.CharField(max_length=200),
        # ),
        # migrations.AlterField(
        #     model_name='routesurveymodel',
        #     name='via_gps',
        #     field=models.CharField(max_length=100),
        # ),
        # migrations.AlterField(
        #     model_name='routesurveymodel',
        #     name='via_place',
        #     field=models.CharField(max_length=200),
        # ),
        migrations.CreateModel(
            name='EquipmentFetModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('markdown_notes', models.TextField(blank=True, null=True, verbose_name='Markdown Notes')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('fet_date', models.DateField(blank=True, null=True)),
                ('fet_status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'), ('fulfilled', 'fulfilled'), ('paid', 'Paid'), ('canceled', 'Canceled'), ('void', 'Void')], default='draft', max_length=15, null=True, verbose_name='FET Item Status')),
                ('draft_date', models.DateField(blank=True, null=True, verbose_name='Draft Date')),
                ('in_review_date', models.DateField(blank=True, null=True, verbose_name='In Review Date')),
                ('approved_date', models.DateField(blank=True, null=True, verbose_name='Approved Date')),
                ('void_date', models.DateField(blank=True, null=True, verbose_name='Void Date')),
                ('fulfillment_date', models.DateField(blank=True, null=True, verbose_name='Fulfillment Date')),
                ('canceled_date', models.DateField(blank=True, null=True, verbose_name='Canceled Date')),
                ('entity', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='aix.entitymodel', verbose_name='EquipmentFet Entity')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aix.customerlocationmodel', verbose_name='Customer Location')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aix.workordermodel', verbose_name='Work Order')),
            ],
            options={
                'verbose_name': 'EquipmentFet',
            },
        ),
        migrations.CreateModel(
            name='ItemFetThroughModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attendance_code', models.CharField(blank=True, choices=[('H', 'Machine operational'), ('S', 'Machine on Standby'), ('OH', 'Machine off Hire'), ('R', 'Machine Under Repair'), ('MOB', 'Mobilization'), ('DMB', 'De-Mobilization'), ('NOS', 'Not/ Nolonger on  site'), ('OPS', 'Operational, at TWS Cost'), ('ES', 'Equipment Serviced')], default='R', max_length=10, null=True)),
                ('attendance_date', models.DateField()),
                ('fet_item_status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='draft', max_length=15, null=True, verbose_name='FET Item Status')),
                ('entity_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='aix.entityunitmodel', verbose_name='Associated Branch')),
                ('equipment_model', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aix.equipmentmodel', verbose_name='Equipment')),
                ('fet_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='aix.equipmentfetmodel', verbose_name='FET Model')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_set', to='aix.itemfetthroughmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='equipmentfetmodel',
            name='fet_items',
            field=models.ManyToManyField(through='aix.ItemFetThroughModel', to='aix.equipmentmodel', verbose_name='FET Items'),
        ),
        migrations.CreateModel(
            name='ItemFetModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, verbose_name='ItemFet Name')),
                ('attendance_code', models.CharField(blank=True, choices=[('H', 'Machine operational'), ('S', 'Machine on Standby'), ('OH', 'Machine off Hire'), ('R', 'Machine Under Repair'), ('MOB', 'Mobilization'), ('DMB', 'De-Mobilization'), ('NOS', 'Not/ Nolonger on  site'), ('OPS', 'Operational, at TWS Cost'), ('ES', 'Equipment Serviced')], max_length=10, null=True)),
                ('attendance_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('entity', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='items_fet', to='aix.entitymodel', verbose_name='ItemFet Entity')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['is_active'], name='aix_itemfet_is_acti_0fbc39_idx'), models.Index(fields=['attendance_code'], name='aix_itemfet_attenda_d11497_idx'), models.Index(fields=['entity', 'attendance_code'], name='aix_itemfet_entity__a3e965_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='itemfetthroughmodel',
            index=models.Index(fields=['fet_model', 'equipment_model'], name='aix_itemfet_fet_mod_d9f02a_idx'),
        ),
        migrations.AddIndex(
            model_name='itemfetthroughmodel',
            index=models.Index(fields=['fet_item_status'], name='aix_itemfet_fet_ite_01b431_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentfetmodel',
            index=models.Index(fields=['created'], name='aix_equipme_created_b86074_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentfetmodel',
            index=models.Index(fields=['updated'], name='aix_equipme_updated_37167f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='equipmentfetmodel',
            unique_together={('entity', 'fet_date', 'location', 'work_order')},
        ),
    ]
