# Generated by Django 5.1.4 on 2025-07-22 08:14

import django.db.models.deletion
import location_field.models.plain
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aix', '0039_equipmenthandovermodel_approved_by_hr_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_by_hr',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approved_by_hr', to='aix.employeemodel', verbose_name='Approved By HR'),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_by_ict',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approved_by_ict', to='aix.employeemodel', verbose_name='Approved By ICT'),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_date_hr',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_date_ict',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='return_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='routesurveymodel',
        #     name='end_gps',
        #     field=models.CharField(max_length=100),
        # ),
        # migrations.AlterField(
        #     model_name='routesurveymodel',
        #     name='end_place',
        #     field=models.CharField(max_length=200),
        # ),
        # migrations.AlterField(
        #     model_name='routesurveymodel',
        #     name='location',
        #     field=location_field.models.plain.PlainLocationField(default=0, max_length=63),
        #     preserve_default=False,
        # ),
        # migrations.AlterField(
        #     model_name='routesurveymodel',
        #     name='start_gps',
        #     field=models.CharField(max_length=100),
        # ),
        # migrations.AlterField(
        #     model_name='routesurveymodel',
        #     name='start_place',
        #     field=models.CharField(max_length=200),
        # ),
        # migrations.AlterField(
        #     model_name='routesurveymodel',
        #     name='via_gps',
        #     field=models.CharField(max_length=100),
        # ),
        # migrations.AlterField(
        #     model_name='routesurveymodel',
        #     name='via_place',
        #     field=models.CharField(max_length=200),
        # ),
        migrations.CreateModel(
            name='EquipmentFuelModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('fuel_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('start_mileage', models.FloatField(blank=True, null=True)),
                ('end_mileage', models.FloatField(blank=True, null=True)),
                ('fuel_qty', models.FloatField(blank=True, null=True)),
                ('fuel_price', models.FloatField(blank=True, null=True)),
                ('fuel_cost', models.FloatField(blank=True, null=True)),
                ('fuel_tank', models.FloatField(blank=True, null=True)),
                ('kms_covered', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('NEW', 'NEW'), ('IN PROGRESS', 'IN PROGRESS'), ('DELAYED', 'DELAYED'), ('POSTPONED', 'POSTPONED'), ('COMPLETED', 'COMPLETED')], default='NEW', max_length=255, null=True)),
                ('end_location', models.ForeignKey(blank=True, db_column='EndLocation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_location_fuel', to='aix.customerlocationmodel')),
                ('entity', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='aix.entitymodel', verbose_name='Equipment Fuel Entity')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aix.equipmentmodel', verbose_name='Equipment')),
                ('fuel_reciept', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aix.documentmodel', verbose_name='Fuel Receipt')),
                ('start_location', models.ForeignKey(blank=True, db_column='StartLocation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_location_fuel', to='aix.customerlocationmodel')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aix.workordermodel', verbose_name='Work Order')),
            ],
            options={
                'verbose_name': 'Equipment Fuel',
                'indexes': [models.Index(fields=['fuel_date'], name='aix_equipme_fuel_da_9a4dee_idx'), models.Index(fields=['equipment'], name='aix_equipme_equipme_c1d551_idx'), models.Index(fields=['start_location'], name='aix_equipme_StartLo_4314de_idx'), models.Index(fields=['end_location'], name='aix_equipme_EndLoca_e9836c_idx'), models.Index(fields=['status'], name='aix_equipme_status_58f7af_idx')],
                'unique_together': {('entity', 'fuel_date', 'equipment', 'work_order', 'start_location')},
            },
        ),
    ]
