# Generated by Django 5.1.4 on 2025-08-20 11:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aix', '0050_equipmenthandovermodel_approved_by_hr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderActivityModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('activity_description', models.TextField(blank=True, null=True)),
                ('work_code', models.CharField(blank=True, choices=[('OPS-TR', 'OPERATIONAL - TRANSPORTATION'), ('OPS-REP', 'OPERATIONAL - REPOSITIONING'), ('OPS-LF', 'OPERATIONAL - LIFTING'), ('STB', 'STANDBY'), ('BRKD', 'BREAKDOWN'), ('OFF-HIRE', 'OFF-HIRE')], max_length=255, null=True)),
                ('etd', models.CharField(blank=True, max_length=255, null=True)),
                ('eta', models.CharField(blank=True, max_length=255, null=True)),
                ('atd', models.CharField(blank=True, max_length=255, null=True)),
                ('ata', models.CharField(blank=True, max_length=255, null=True)),
                ('etp', models.FloatField(blank=True, default=0.0, null=True)),
                ('atp', models.FloatField(blank=True, default=0.0, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('New', 'New'), ('Mobilizing', 'Mobilizing'), ('Progress', 'In Progress'), ('Completed', 'Completed')], default='New', max_length=255, null=True)),
                ('is_work_location', models.BooleanField(default=True)),
                ('entity', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='aix.entitymodel', verbose_name='WorkOrderActivity Entity')),
                ('from_location', models.ForeignKey(blank=True, db_column='FromLocation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_from_location', to='aix.customerlocationmodel')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aix.workordertaskmodel', verbose_name='Task')),
                ('to_location', models.ForeignKey(blank=True, db_column='ToLocation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_to_location', to='aix.customerlocationmodel')),
            ],
            options={
                'verbose_name': 'WorkOrderActivity',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderActivityAssetModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default='NA', max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('DISABLED', 'DISABLED')], default='ACTIVE', max_length=255, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aix.assetmodel', verbose_name='Asset')),
                ('entity', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='aix.entitymodel', verbose_name='WorkOrder Type Entity')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aix.workorderactivitymodel', verbose_name='Activity')),
            ],
            options={
                'verbose_name': 'Work Order Asset',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderActivityPersonnelModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default='NA', max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('wostatus', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('DISABLED', 'DISABLED')], default='ACTIVE', max_length=255, null=True)),
                ('deploy_date', models.DateField()),
                ('relieve_date', models.DateField()),
                ('duties', models.TextField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aix.workorderactivitymodel', verbose_name='Activity')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aix.employeemodel', verbose_name='Employee')),
                ('entity', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='aix.entitymodel', verbose_name='Work Order Personnel Entity')),
            ],
            options={
                'verbose_name': 'Work Order Personnel',
            },
        ),
        migrations.AddIndex(
            model_name='workorderactivitymodel',
            index=models.Index(fields=['activity_date'], name='aix_workord_activit_5db10b_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderactivitymodel',
            index=models.Index(fields=['activity_description'], name='aix_workord_activit_bf3976_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderactivitymodel',
            index=models.Index(fields=['comments'], name='aix_workord_comment_87cf9b_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderactivitymodel',
            index=models.Index(fields=['status'], name='aix_workord_status_b3a933_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workorderactivitymodel',
            unique_together={('entity', 'activity_date', 'from_location', 'to_location', 'task')},
        ),
        migrations.AddIndex(
            model_name='workorderactivityassetmodel',
            index=models.Index(fields=['start_date'], name='aix_workord_start_d_16812d_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderactivityassetmodel',
            index=models.Index(fields=['end_date'], name='aix_workord_end_dat_79c848_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderactivityassetmodel',
            index=models.Index(fields=['status'], name='aix_workord_status_9a703e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workorderactivityassetmodel',
            unique_together={('entity', 'start_date', 'end_date', 'activity', 'asset')},
        ),
        migrations.AddIndex(
            model_name='workorderactivitypersonnelmodel',
            index=models.Index(fields=['start_date'], name='aix_workord_start_d_da91ca_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderactivitypersonnelmodel',
            index=models.Index(fields=['end_date'], name='aix_workord_end_dat_97b4ae_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderactivitypersonnelmodel',
            index=models.Index(fields=['status'], name='aix_workord_status_1e4382_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workorderactivitypersonnelmodel',
            unique_together={('entity', 'start_date', 'end_date', 'activity', 'employee')},
        ),
    ]
