# Generated by Django 5.1.4 on 2025-08-21 13:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aix', '0051_workorderactivitymodel_workorderactivityassetmodel_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_by_hr',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approved_by_hr', to='aix.employeemodel', verbose_name='Approved By HR'),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_by_ict',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approved_by_ict', to='aix.employeemodel', verbose_name='Approved By ICT'),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_date_hr',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_date_ict',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='return_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
        migrations.CreateModel(
            name='WorkOrderActivityDocumentModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default='NA', max_length=100)),
                ('doc_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('DRAFT', 'DRAFT'), ('APPROVED', 'APPROVED'), ('DISABLED', 'DISABLED'), ('REJECTED', 'REJECTED'), ('SIGNED', 'SIGNED')], default='ACTIVE', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aix.workorderactivitymodel', verbose_name='Activity Document')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aix.documentmodel', verbose_name='Activity Document')),
                ('entity', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='aix.entitymodel', verbose_name='WorkOrder Type Entity')),
            ],
            options={
                'verbose_name': 'Work Order Document',
                'indexes': [models.Index(fields=['doc_date'], name='aix_workord_doc_dat_adb9d6_idx'), models.Index(fields=['description'], name='aix_workord_descrip_4371e3_idx'), models.Index(fields=['status'], name='aix_workord_status_2caead_idx')],
                'unique_together': {('entity', 'doc_date', 'activity', 'document', 'status')},
            },
        ),
    ]
