# Generated by Django 5.1.4 on 2025-08-26 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aix', '0054_equipmenthandovermodel_approved_by_hr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmodel',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='aix.workorderactivitymodel', verbose_name='Activity'),
        ),
        migrations.AddField(
            model_name='documentmodel',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='aix.workordertaskmodel', verbose_name='Task'),
        ),
        migrations.AddField(
            model_name='documentmodel',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='aix.workordermodel', verbose_name='Work Order'),
        ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_by_hr',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approved_by_hr', to='aix.employeemodel', verbose_name='Approved By HR'),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_by_ict',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approved_by_ict', to='aix.employeemodel', verbose_name='Approved By ICT'),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_date_hr',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_date_ict',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='return_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
    ]
