# Generated by Django 5.1.4 on 2025-08-26 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aix', '0055_documentmodel_activity_documentmodel_task_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_by_hr',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approved_by_hr', to='aix.employeemodel', verbose_name='Approved By HR'),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_by_ict',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approved_by_ict', to='aix.employeemodel', verbose_name='Approved By ICT'),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_date_hr',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_date_ict',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='return_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
        migrations.AlterField(
            model_name='documentmodel',
            name='mime_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='documentmodel',
            name='name_on_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='documentmodel',
            name='size',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
