# Generated by Django 5.1.4 on 2025-09-02 08:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aix', '0057_equipmenthandovermodel_approved_by_hr_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_by_hr',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approved_by_hr', to='aix.employeemodel', verbose_name='Approved By HR'),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_by_ict',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approved_by_ict', to='aix.employeemodel', verbose_name='Approved By ICT'),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_date_hr',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_date_ict',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='return_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
        migrations.CreateModel(
            name='WorkOrderActivityLiftingModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default='NA', max_length=100)),
                ('trip_code', models.CharField(blank=True, choices=[('OPS-TR', 'OPERATIONAL - TRANSPORTATION'), ('OPS-REP', 'OPERATIONAL - REPOSITIONING'), ('OPS-LF', 'OPERATIONAL - LIFTING'), ('STB', 'STANDBY'), ('BRKD', 'BREAKDOWN'), ('OFF-HIRE', 'OFF-HIRE')], max_length=255, null=True)),
                ('operators', models.JSONField(null=True)),
                ('status', models.CharField(blank=True, choices=[('New', 'New'), ('Mobilizing', 'Mobilizing'), ('Progress', 'In Progress'), ('Completed', 'Completed')], default='NEW', max_length=255, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aix.workorderactivitymodel', verbose_name='Activity')),
                ('entity', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='aix.entitymodel', verbose_name='Work Order Lifting Entity')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='equipment_lifting', to='aix.assetmodel', verbose_name='Equipment')),
                ('from_location', models.ForeignKey(blank=True, db_column='FromLocation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_location_lifting', to='aix.customerlocationmodel')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='operator_lifting', to='aix.employeemodel', verbose_name='Operator')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='supervisor_lifting', to='aix.employeemodel', verbose_name='Supervisor')),
                ('to_location', models.ForeignKey(blank=True, db_column='ToLocation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_location_lifting', to='aix.customerlocationmodel')),
            ],
            options={
                'verbose_name': 'Work Order Lifting',
                'indexes': [models.Index(fields=['trip_code'], name='aix_workord_trip_co_e78ae8_idx'), models.Index(fields=['comments'], name='aix_workord_comment_0d85ad_idx'), models.Index(fields=['status'], name='aix_workord_status_69d1b5_idx')],
                'unique_together': {('entity', 'activity', 'trip_code', 'operator', 'equipment')},
            },
        ),
        migrations.CreateModel(
            name='WorkOrderActivityTransportModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default='NA', max_length=100)),
                ('trip_code', models.CharField(blank=True, choices=[('OPS-TR', 'OPERATIONAL - TRANSPORTATION'), ('OPS-REP', 'OPERATIONAL - REPOSITIONING'), ('OPS-LF', 'OPERATIONAL - LIFTING'), ('STB', 'STANDBY'), ('BRKD', 'BREAKDOWN'), ('OFF-HIRE', 'OFF-HIRE')], max_length=255, null=True)),
                ('etd', models.CharField(blank=True, max_length=255, null=True)),
                ('eta', models.CharField(blank=True, max_length=255, null=True)),
                ('atd', models.CharField(blank=True, max_length=255, null=True)),
                ('ata', models.CharField(blank=True, max_length=255, null=True)),
                ('etp', models.FloatField(blank=True, default=0.0, null=True)),
                ('atp', models.FloatField(blank=True, default=0.0, null=True)),
                ('status', models.CharField(blank=True, choices=[('New', 'New'), ('Mobilizing', 'Mobilizing'), ('Progress', 'In Progress'), ('Completed', 'Completed')], default='ACTIVE', max_length=255, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aix.workorderactivitymodel', verbose_name='Activity')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aix.employeemodel', verbose_name='Driver')),
                ('entity', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='aix.entitymodel', verbose_name='Work Order Transport Entity')),
                ('from_location', models.ForeignKey(blank=True, db_column='FromLocation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_location_transport', to='aix.customerlocationmodel')),
                ('to_location', models.ForeignKey(blank=True, db_column='ToLocation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_location_transport', to='aix.customerlocationmodel')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aix.assetmodel', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Work Order Transport',
                'indexes': [models.Index(fields=['trip_code'], name='aix_workord_trip_co_ef770b_idx'), models.Index(fields=['comments'], name='aix_workord_comment_20a9bc_idx'), models.Index(fields=['status'], name='aix_workord_status_abfaaa_idx')],
                'unique_together': {('entity', 'activity', 'trip_code', 'driver', 'vehicle')},
            },
        ),
    ]
