# Generated by Django 5.1.4 on 2025-09-02 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aix', '0058_equipmenthandovermodel_approved_by_hr_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_by_hr',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approved_by_hr', to='aix.employeemodel', verbose_name='Approved By HR'),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_by_ict',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approved_by_ict', to='aix.employeemodel', verbose_name='Approved By ICT'),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_date_hr',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='approved_date_ict',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='equipmenthandovermodel',
        #     name='return_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
        migrations.RemoveField(
            model_name='workorderactivityliftingmodel',
            name='operators',
        ),
        migrations.AddField(
            model_name='workorderactivityliftingmodel',
            name='operators',
            field=models.ManyToManyField(blank=True, related_name='operators_lifting', to='aix.employeemodel', verbose_name='Operators'),
        ),
    ]
