# Generated by Django 4.2.7 on 2024-02-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmodel',
            name='wialon_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
