# Generated by Django 4.2.7 on 2024-03-08 15:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('aix', '0002_assetmodel_wialon_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmodel',
            name='id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workordermodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='workordermodel',
            name='service_type',
            field=models.CharField(blank=True, choices=[('TRANSPORT AND LIFTING', 'TRANSPORT AND LIFTING'), ('LIFTING ONLY', 'LIFTING ONLY'), ('TRANSPORT ONLY', 'TRANSPORT ONLY')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workordermodel',
            name='status',
            field=models.CharField(blank=True, choices=[('NEW', 'NEW'), ('IN PROGRESS', 'IN PROGRESS'), ('DELAYED', 'DELAYED'), ('POSTPONED', 'POSTPONED'), ('COMPLETED', 'COMPLETED')], default='NEW', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='UserAllocationModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('entity', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_allocation', to='aix.entitymodel', verbose_name='UserAllocation Entity')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aix.workordertaskmodel', verbose_name='Work Order Task')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aix.workordermodel', verbose_name='Work Order')),
            ],
            options={
                'verbose_name': 'UserAllocation',
                'indexes': [models.Index(fields=['created'], name='aix_useral_created_d7ce72_idx'), models.Index(fields=['updated'], name='aix_useral_updated_0cc3c9_idx'), models.Index(fields=['work_order'], name='aix_useral_work_or_75bd01_idx'), models.Index(fields=['task'], name='aix_useral_task_id_1cb075_idx')],
                'unique_together': {('entity', 'work_order', 'task')},
            },
        ),
    ]
