# Generated by Django 4.2.7 on 2024-03-08 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aix', '0003_assetmodel_id_alter_workordermodel_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userallocationmodel',
            name='allocation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='allocated_to', to=settings.AUTH_USER_MODEL, verbose_name='Allocation'),
            preserve_default=False,
        ),
    ]
