# Generated by Django 4.2.7 on 2024-03-08 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aix', '0005_alter_userallocationmodel_task_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userallocationmodel',
            name='aix_useral_work_or_75bd01_idx',
        ),
        migrations.RemoveIndex(
            model_name='userallocationmodel',
            name='aix_useral_task_id_1cb075_idx',
        ),
    ]
