# Generated by Django 4.2.7 on 2024-03-08 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aix', '0006_remove_userallocationmodel_aix_useral_work_or_75bd01_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userallocationmodel',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='aix.workordertaskmodel', verbose_name='Work Order Task'),
        ),
        migrations.AlterField(
            model_name='userallocationmodel',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='aix.workordermodel', verbose_name='Work Order'),
        ),
    ]
