# Generated by Django 4.2.7 on 2024-03-21 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aix', '0007_alter_userallocationmodel_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpipobmodel',
            name='work_order',
        ),
        migrations.AddField(
            model_name='kpipobmodel',
            name='task',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='aix.workordertaskmodel', verbose_name='Work Order Task'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kpiopsmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Mobilizing', 'Mobilizing'), ('Progress', 'In Progress'), ('Completed', 'Completed')], default='New', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userallocationmodel',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_allocation', to='aix.entitymodel', verbose_name='UserAllocation Entity'),
        ),
        migrations.AlterField(
            model_name='workordertaskassetmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('DISABLED', 'DISABLED')], default='ACTIVE', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workordertaskmodel',
            name='currentstatus',
            field=models.CharField(blank=True, choices=[('NEW', 'NEW'), ('IN PROGRESS', 'IN PROGRESS'), ('DELAYED', 'DELAYED'), ('POSTPONED', 'POSTPONED'), ('COMPLETED', 'COMPLETED')], db_column='currentStatus', default='NEW', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workordertaskpersonnelmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('DISABLED', 'DISABLED')], default='ACTIVE', max_length=255, null=True),
        ),
    ]
