# Generated by Django 4.2.7 on 2024-03-21 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aix', '0008_remove_kpipobmodel_work_order_kpipobmodel_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpionoffmodel',
            name='task',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='aix.workordertaskmodel', verbose_name='Work Order Task'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kpipobmodel',
            name='work_order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='aix.workordermodel', verbose_name='Work Order'),
            preserve_default=False,
        ),
    ]
