# Generated by Django 4.2.7 on 2024-03-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aix', '0009_kpionoffmodel_task_kpipobmodel_work_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpionoffmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Mobilizing', 'Mobilizing'), ('Progress', 'In Progress'), ('Completed', 'Completed')], default='New', max_length=255, null=True),
        ),
    ]
