# Generated by Django 4.2.7 on 2024-03-21 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aix', '0010_alter_kpionoffmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpionoffmodel',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='aix.workordertaskmodel', verbose_name='Work Order Task'),
        ),
    ]
