# Generated by Django 4.2.7 on 2024-03-21 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aix', '0011_alter_kpionoffmodel_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpipobmodel',
            name='activity_location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='aix.customerlocationmodel', verbose_name='Customer Location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kpipobmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Mobilizing', 'Mobilizing'), ('Progress', 'In Progress'), ('Completed', 'Completed')], default='New', max_length=255, null=True),
        ),
    ]
