# Generated by Django 4.2.7 on 2024-03-21 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aix', '0012_alter_kpipobmodel_activity_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpionoffmodel',
            name='work_order',
        ),
        migrations.RemoveField(
            model_name='kpipobmodel',
            name='work_order',
        ),
        migrations.AlterField(
            model_name='kpipobmodel',
            name='activity_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='aix.customerlocationmodel', verbose_name='Activity Location'),
        ),
    ]
