# Generated by Django 4.2.7 on 2024-03-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aix', '0013_remove_kpionoffmodel_work_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
