"""
Contributions to this module:
Miguel Sanda <msanda@arrobalytics.com>
Mando <mandonpolo@gmail.com>
"""

from aix.views.account import *
from aix.views.auth import *
from aix.views.bank_account import *
from aix.views.home import *
from aix.views.bill import *
from aix.views.coa import *
from aix.views.customer import *
from aix.views.djl_api import *
from aix.views.entity import *
from aix.views.inventory import *
from aix.views.invoice import *
from aix.views.item import *
from aix.views.journal_entry import *
from aix.views.ledger import *
from aix.views.purchase_order import *
from aix.views.unit import *


#from aix.views.account_code_prefix import *
from aix.views.absence_date import *
from aix.views.absence_type import *
from aix.views.aix_its_status_report import *
from aix.views.announcement import *
from aix.views.asset import *
from aix.views.attached_email import *
from aix.views.benefit_calculation import *
from aix.views.benefit_type import *
from aix.views.benefit import *
from aix.views.business_industry import *
from aix.views.currency_rate import *
from aix.views.currency import *
from aix.views.customer import *
from aix.views.customer_location import *
from aix.views.department import *
from aix.views.dependant import *
from aix.views.document_status import *
from aix.views.document_type import *
from aix.views.document import *
from aix.views.education import *
from aix.views.employee_assignment import *
from aix.views.employee_avatar import *
from aix.views.employee_contract_type import *
from aix.views.employee_contract import *
from aix.views.employee_faw import *
from aix.views.employee_language import *
from aix.views.employee_license_detail import *
from aix.views.employee_license_type import *
from aix.views.employee_of_the_week import *
from aix.views.employee_payroll_benefit import *
from aix.views.employee_payroll import *
#from aix.views.employee_transaction import *
from aix.views.employee import *
from aix.views.equipment import *
from aix.views.equipment_assignment import *
from aix.views.equipment_axle import *
from aix.views.equipment_fet import *
from aix.views.equipment_fuel import *
from aix.views.equipment_handover import *
from aix.views.equipment_join import *
from aix.views.equipment_manufacturer import *
from aix.views.equipment_type import *
from aix.views.general_notification import *
from aix.views.holiday import *
from aix.views.immigration_detail import *
from aix.views.incoming_document_handler import *
from aix.views.incoming_document_type import *
from aix.views.incoming_document import *
from aix.views.insurance_detail import *
from aix.views.invoice_action import *
from aix.views.invoice_status import *
from aix.views.invoice_type import *
from aix.views.invoice import *
from aix.views.job import *
from aix.views.kpihse import *
from aix.views.kpionoff import *
from aix.views.kpiops import *
from aix.views.kpipob import *
from aix.views.language import *
from aix.views.leave_card_carried_over import *
from aix.views.leave_card_detail import *
from aix.views.leave_card import *
from aix.views.leave_request_action import *
from aix.views.leave_request_detail import *
from aix.views.leave_request_status import *
from aix.views.leave_request_workflow_action import *
from aix.views.leave_request_workflow import *
from aix.views.leave_request import *
from aix.views.locations import *
from aix.views.marital_status import *
from aix.views.nation import *
from aix.views.notification_external_type import *
from aix.views.notification_tracker import *
from aix.views.notification import *
from aix.views.payment_mode import *
from aix.views.payroll_advance_request_action import *
from aix.views.payroll_advance_request_detail import *
from aix.views.payroll_advance_request_status import *
from aix.views.payroll_advance_request_workflow_action import *
from aix.views.payroll_advance_request_workflow import *
from aix.views.payroll_advance_request import *
from aix.views.payroll_advance import *
from aix.views.qualification import *
# from aix.views.received_email_document import *
from aix.views.relationship import *
from aix.views.reporter import *
from aix.views.requisition_action import *
from aix.views.requisition_category import *
from aix.views.requisition_flow_type import *
from aix.views.requisition_status import *
from aix.views.requisition_workflow_action import *
from aix.views.requisition_workflow import *
from aix.views.requisition import *
from aix.views.route_survey import *
from aix.views.route_survey_info import *
from aix.views.salary import *
from aix.views.skill import *
from aix.views.settings import *
from aix.views.task_assignee import *
from aix.views.task_status import *
from aix.views.task import *
from aix.views.tax import *
from aix.views.visa import *
from aix.views.weekend import *
from aix.views.weekly_employee_processed import *
from aix.views.weekly_employee import *
from aix.views.work_order_activity import *
from aix.views.work_order_activity_asset import *
from aix.views.work_order_activity_lifting import *
from aix.views.work_order_activity_document import *
from aix.views.work_order_activity_personnel import *
from aix.views.work_order_activity_transport import *
from aix.views.work_category import *
from aix.views.work_order_asset import *
from aix.views.work_order_personnel import *
from aix.views.work_order_status import *
from aix.views.work_order_jobcard_status import *
from aix.views.work_order_jobcard import *
from aix.views.work_order_type import *
from aix.views.work_order import *
from aix.views.work_order_task import *
from aix.views.work_order_task_asset import *
from aix.views.work_order_task_personnel import *
from aix.views.workflow_action_type import *
from aix.views.workflow_action import *
from aix.views.workflow_status import *
from aix.views.workflow_type import *
from aix.views.workflow import *

from aix.views.estimate import *
from aix.views.data_import import *
from aix.views.transactions import *
from aix.views.vendor import *