"""
Contributions to this module:
Miguel Sanda <msanda@arrobalytics.com>
Mando <mandonpolo@gmail.com>
"""
from aix.models.data_import import *
from aix.models.entity import *

from aix.models.absence_date import *
from aix.models.absence_type import *
from aix.models.accounts import *
from aix.models.account_code_prefix import *
from aix.models.announcement import *
from aix.models.asset import *
from aix.models.aix_its_handover import *
from aix.models.aix_its_status_report import *
from aix.models.attached_email import *
from aix.models.bank_account import *
from aix.models.benefit_calculation import *
from aix.models.benefit_type import *
from aix.models.benefit import *
from aix.models.bill import *
from aix.models.business_industry import *
from aix.models.coa_default import *
from aix.models.coa import *
from aix.models.currency_rate import *
from aix.models.currency import *
from aix.models.customer import *
from aix.models.customer_location import *
from aix.models.department import *
from aix.models.dependant import *
from aix.models.document_status import *
from aix.models.document_type import *
from aix.models.document import *
from aix.models.education import *
from aix.models.equipment import *
from aix.models.equipment_axle import *
from aix.models.equipment_type import *
from aix.models.equipment_manufacturer import *
from aix.models.employee_assignment import *
from aix.models.employee_avatar import *
from aix.models.employee_contract_type import *
from aix.models.employee_contract import *
from aix.models.employee_faw_items import *
from aix.models.employee_faw import *
from aix.models.employee_language import *
from aix.models.employee_license_detail import *
from aix.models.employee_license_type import *
from aix.models.employee_of_the_week import *
from aix.models.employee_payroll_benefit import *
from aix.models.employee_payroll import *
from aix.models.employee_transaction import *
from aix.models.employee import *
from aix.models.equipment import *
from aix.models.equipment_assignment import *
from aix.models.equipment_axle import *
from aix.models.equipment_fet_items import *
from aix.models.equipment_fet import *
from aix.models.equipment_fuel import *
from aix.models.equipment_handover import *
from aix.models.equipment_join import *
from aix.models.equipment_manufacturer import *
from aix.models.general_notification import *
from aix.models.holiday import *
from aix.models.immigration_detail import *
from aix.models.incoming_document_handler import *
from aix.models.incoming_document_type import *
from aix.models.incoming_document import *
from aix.models.insurance_detail import *
from aix.models.invoice_action import *
from aix.models.invoice_status import *
from aix.models.invoice_type import *
from aix.models.invoice import *
from aix.models.items import *
from aix.models.job_applicant import *
from aix.models.job_category import *
from aix.models.job import *
from aix.models.journalentry import *
from aix.models.kpihse import *
from aix.models.kpionoff import *
from aix.models.kpiops import *
from aix.models.kpipob import *
from aix.models.leave_card_carried_over import *
from aix.models.leave_card_detail import *
from aix.models.leave_card import *
from aix.models.leave_request_action import *
from aix.models.leave_request_detail import *
from aix.models.leave_request_status import *
from aix.models.leave_request_workflow_action import *
from aix.models.leave_request_workflow import *
from aix.models.leave_request import *
from aix.models.ledger import *
from aix.models.locations import *
from aix.models.marital_status import *
from aix.models.mixins import *
from aix.models.nation import *
from aix.models.notification_external_type import *
from aix.models.notification_tracker import *
from aix.models.notification import *
from aix.models.payment_mode import *
from aix.models.payroll_advance_request_action import *
from aix.models.payroll_advance_request_detail import *
from aix.models.payroll_advance_request_status import *
from aix.models.payroll_advance_request_workflow_action import *
from aix.models.payroll_advance_request_workflow import *
from aix.models.payroll_advance_request import *
from aix.models.payroll_advance import *
from aix.models.qualification import *
from aix.models.received_email_document import *
from aix.models.relationship import *
from aix.models.reporter import *
from aix.models.requisition_action import *
from aix.models.requisition_category import *
from aix.models.requisition_flow_type import *
from aix.models.requisition_status import *
from aix.models.requisition_workflow_action import *
from aix.models.requisition_workflow import *
from aix.models.requisition import *
from aix.models.route_survey import *
from aix.models.route_survey_info import *
from aix.models.salary import *
from aix.models.skill import *
from aix.models.task_assignee import *
from aix.models.task_status import *
from aix.models.task import *
from aix.models.tax import *
from aix.models.transactions import *
from aix.models.unit import *
from aix.models.user_allocation import *
from aix.models.vendor import *
from aix.models.visa import *
from aix.models.weekend import *
from aix.models.weekly_employee_processed import *
from aix.models.weekly_employee import *
from aix.models.work_category import *
from aix.models.work_order_asset import *
from aix.models.work_order_activity_asset import *
from aix.models.work_order_activity_document import *
from aix.models.work_order_activity_lifting import *
from aix.models.work_order_activity_personnel import *
from aix.models.work_order_activity_transport import *
from aix.models.work_order_activity import *
from aix.models.work_order_status import *
from aix.models.work_order_jobcard_status import *
from aix.models.work_order_jobcard import *
from aix.models.work_order_personnel import *
from aix.models.work_order_status import *
from aix.models.work_order_task_asset import *
from aix.models.work_order_task_personnel import *
from aix.models.work_order_task import *
from aix.models.work_order_type import *
from aix.models.work_order import *
from aix.models.workflow_action_type import *
from aix.models.workflow_action import *
from aix.models.workflow_status import *
from aix.models.workflow_type import *
from aix.models.workflow import *

from aix.models.estimate import *
from aix.models.language import *
from aix.models.purchase_order import *